title: Mohammad Reza Fathnejad # your name
logo: "images/me.jpg" # photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Hi There!<br>
  Second description 
  <br>Welcome to my Portfolio.<br>
  <a href="https://www.linkedin.com/in/mohammad-fathnejad/">LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
