title: Mohammad Reza Fathnejad # your name
logo: "images/me.jpg" # photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Hi There!<br>
  <br><br>
  <br>Welcome to my Portfolio.<br>
  <a href="https://www.linkedin.com/in/mohammad-fathnejad/">LinkedIn Profile</a> 
  
theme: jekyll-theme-tactile
google_analytics: UA-152683784-1 # your Google Analytics tracking ID here
